### ISSUE TITLE
Connected with Shreya for Beckn-Onix Issue

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#162]
## Description
We need to address an issue encountered in the Beckn-Onix system. A meeting with Shreya has been scheduled to discuss the problem, identify the root cause, and determine the necessary steps to resolve it. 

## Goals
- Understand the Beckn-Onix issue in detail.
- Identify the root cause of the problem.
- Develop a plan to resolve the issue.

## Expected Outcome
A clear understanding of the Beckn-Onix issue, a documented plan for resolution, and a functional Beckn-Onix system.

## Acceptance Criteria
- [ ] Identify and document the root cause of the issue.
- [ ] Develop and implement a fix for the identified issue.
- [ ] Verify that the Beckn-Onix system functions correctly post-fix.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
Beckn-Onix

## Tech Skills Needed
- Troubleshooting and debugging
- System management
- Communication and collaboration

## Complexity
Medium

## Category
Bug Fix

## Sub Category
System Issue

**Comment by prasad-takale-eminds** [comment]
We were facing issue when deploying Beckn application using beckn-onix script on MacOS. 
Below is the error message. 
```The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested```
We did the required changes in docker-compose.yml file and tested it and it was working fine. 
But this issue was for Mac user only so for the conveniences we have update the installation document with below steps which resolved the issue  on MacOS. 
We have tested this on Shreya Mac machine. 
Command we used to resolve the issue. 
```export DOCKER_DEFAULT_PLATFORM=linux/amd64```
