### ISSUE TITLE
Helm Chart Deployment on AWS EKS Cluster

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#223]
## Description
Deploy the Registry, Gateway, BAP, and BPP services on an AWS EKS Cluster using the Helm chart provided by the AWS team. The deployment should follow the guidelines and instructions detailed in the documentation provided by the AWS team. Ensure that all services are correctly deployed and configured, and validate that the services function as expected post-deployment.

## Goals
- [x] Deploy the Registry service on AWS EKS using the provided Helm chart.
- [x] Deploy the Gateway service on AWS EKS using the provided Helm chart.
- [x] Deploy the BAP (Buyer Application Platform) on AWS EKS using the provided Helm chart.
- [x] Deploy the BPP (Buyer Provider Platform) on AWS EKS using the provided Helm chart.
- [ ] Follow the documentation provided by the AWS team to ensure accurate deployment.
- [x] Validate the correct functioning of all services post-deployment.

## Expected Outcome
- All services (Registry, Gateway, BAP, BPP) are successfully deployed on the AWS EKS Cluster using Helm charts.
- The deployment process follows the AWS team's documentation.
- Post-deployment validation confirms that the services function as expected.

## Acceptance Criteria
- [ ] Registry service is successfully deployed on AWS EKS using the Helm chart.
- [x] Gateway service is successfully deployed on AWS EKS using the Helm chart.
- [ ] BAP service is successfully deployed on AWS EKS using the Helm chart.
- [ ] BPP service is successfully deployed on AWS EKS using the Helm chart.
- [ ] All services pass post-deployment validation and are functional.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
- AWS EKS
- Helm Charts
- Kubernetes
- Registry, Gateway, BAP, BPP Services
- AWS Documentation Follow-up

## Complexity
Medium

## Category
Deployment

## Sub Category
Kubernetes Deployment

**Comment by prasad-takale-eminds** [comment]
Update on 17th Sept 2024. 

Today, I worked on helm testing. Here are the key points:

- Created a new EKS cluster because the previous one had an underscore (_) in the name, preventing the creation of the Load Balancer (LB) controller.
- After setting up the new cluster, we encountered an error when installing the registry. The issue was due to an incorrect Kubernetes manifest file that hadn't been pushed to the Git repo.
- The Gateway is not getting the SUBSCRIBE status automatically. Even after executing the `/bg/subscribe` API, the Gateway is not switching to the subscribed status.
- The LB initially used a private subnet, making the registry inaccessible from outside the EKS cluster.
- I had to attach at least two public subnets to resolve the LB controller issue. After creating an additional public subnet and attaching it to the EKS cluster, the LB controller issue was fixed.
- For the LB controller, we needed to tag the subnets and attach them to the EKS cluster.
- For BAP and BPP common services, we had to manually create an EFS volume, which was not mentioned in the documentation.
- During BAP and BPP installation, the IAM permissions had to be updated to create the necessary EBS volumes.
- I attempted to install BAP and BPP using the helm chart, but the application is still not up and running.

**Comment by prasad-takale-eminds** [comment]
For now, this activity is on hold as mentioned by Ravi.  We were using Ekstep's AWS account for this testing. 

Helm deployment for BAP and BPP is failing. 
SS for failure. 
![Image](https://github.com/user-attachments/assets/afd925b1-a1e9-4f4a-987c-15250c05ab2f)

![Image](https://github.com/user-attachments/assets/6d551dda-9103-43b2-873a-767efd9ea80d)
