### ISSUE TITLE
Search Provider - Testing New Gateway Instance Using Postman Collections

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#96]
### Description
After creating the new Gateway instance on AWS using ONIX and pointing the existing registry of the BOC environment to this new Gateway (`gateway-boc.becknprotocol.io`), there should be testing conducted using the Postman collections. This is to ensure that the request and response flow correctly as they exist in the Sandbox environment.

### Goals
- [ ] Test the new Gateway instance using Postman collections.
- [ ] Verify that requests and responses are functioning correctly.
- [ ] Ensure that the new Gateway is properly integrated with the BOC environment registry.

### Expected Outcome
Successful verification of the new Gateway instance, ensuring that requests and responses work as expected using the Postman collections in the Sandbox environment.

### Acceptance Criteria
- [ ] Postman collections are used to test the new Gateway instance.
- [ ] Requests and responses are verified to function correctly.
- [ ] Successful integration of the new Gateway with the BOC environment registry is confirmed.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Backend

### Tech Skills Needed
- API Testing
- Postman

### Complexity
Medium

### Category
Backend Development

### Sub Category
Testing

**Comment by prasad-takale-eminds** [comment]
We did one round of testing using Postman and we have received a response from https://gateway-boc.becknprotocol.io. 
Please find the screenshot for the same. 


![Image](https://github.com/beckn/beckn-onix/assets/84436945/4cfbac01-6c7a-4814-9855-111ed84fd5fa)

@shreyvishal Will add more inputs on it.

**Comment by shreyvishal** [comment]
As per current implementation of Protocol server, it looks for a list of gateways that are present in the registry and then it iterates through the list and broadcast the request to the gateways in sequence and if the gateway present in that current iteration fails to send back an `ACK` then only it will send request to next gateway otherwise on successful response from the gateway will stop the iteration and return from the function. So in case of testing any specific gateway there should not be any working existing gateway present in the registry as the gateway to be tested will not be notified with the request.
cc: @viraj89 @faizmagic
